server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opensearch_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Pratiksha@25
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

opensearch:
  hosts: localhost:9200
  scheme: http
  username:
  password:
